// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = "TEST12345";    // Network SSID (name)
const char PASS[]     = "12345678";    // Network password (use for WPA, or use as key for WEP)

void onPhChange();
void onTdsChange();
void onTempChange();
void onTurbidityChange();
void onNotificationChange();


String notification;
float ph;
float tds;
float temp;
float turbidity;


void initProperties(){

  ArduinoCloud.addProperty(notification, READWRITE, ON_CHANGE, onNotificationChange);
  ArduinoCloud.addProperty(ph, READWRITE, ON_CHANGE, onPhChange);
  ArduinoCloud.addProperty(tds, READWRITE, ON_CHANGE, onTdsChange);
  ArduinoCloud.addProperty(temp, READWRITE, ON_CHANGE, onTempChange);
  ArduinoCloud.addProperty(turbidity, READWRITE, ON_CHANGE, onTurbidityChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
